
title: "CRDT Web Caching: Additional Material"
author: Markus Sosnowski
baseurl: "/crdt-web-caching" # the subpath of your site, e.g. /blog
url: "https://tumi8.github.io"

github_ssh: git@github.com:tumi8/crdt-web-caching.git
github_link: https://github.com/tumi8/crdt-web-caching

github_username: syncall

remote_theme: tumi8/tumi8-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme


syntax_highlighter_style: github

collections:
  pages:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
